#!/usr/bin/env bash
#is a challenge

check_factor() {
    if [ $# -ne 3 ]; then
        args=("$@")
        count=0
        num2=1
        for a in "${args[@]}"; do
            if [ $count -gt 1 ]; then
                num2=$(echo "$a*$num2" | bc)
            fi
            count=$((count + 1))
        done
    else
        num2=$3
    fi

    num1=$2
    num=$(echo "$1" | tr ':' '=')

    result=$(echo "$num2 > $num1"
